export const defaults = Object.freeze({
  nodeEnv: 'development',
  botName: 'SkyVerse',
  prefix: '.',
  logLevel: 'info',
  authPath: './sessions/whatsapp',
  databasePath: './data/skyverse.sqlite',
  depayBaseUrl: 'https://depay.cloud',
  keyraBaseUrl: 'https://www.keyrafara.com',
  keyraApiKey: null,
  removeBgBaseUrl: 'https://clearbackdrop.com/api/v1',
  menuBannerEnabled: true,
  menuBannerImage: 'https://raw.githubusercontent.com/irhsrykhan01/skyverse/main/file_000000007a90720880001aa9bde3c4b7.png',
  menuBannerLink: null,
  menuBannerTitle: 'Support SkyVerse',
  menuBannerBody: 'Dukung pengembangan SkyVerse',
  whatsappLogLevel: 'silent',
  autoRead: true,
  autoOnline: true,
});
