export const defaults = Object.freeze({
  nodeEnv: 'development',
  botName: 'SkyVerse',
  prefix: '.',
  logLevel: 'info',
  authPath: './sessions/whatsapp',
  databasePath: './data/skyverse.sqlite',
  depayBaseUrl: 'https://depay.cloud',
  keyraBaseUrl: 'https://www.keyrafara.com',
  keyraApiKey: null,
  bratBaseUrl: 'https://aqul-brat.hf.space',
  nexrayBaseUrl: 'https://api.nexray.web.id',
  removeBgBaseUrl: 'https://clearbackdrop.com/api/v1',
  whatsappLogLevel: 'silent',
  autoRead: true,
  autoOnline: true,
});
